Updated general section and more detailed action/services description 2nd attempt
svrooij/sonos-api-docs pull request #19
Opened 2021-08-19 08:52 UTC by hklages

- general section: example for SOAP request and remark about SONOS boolean (1 and not true)
- added description for more services (now only virtual line in is missing)
- added Servicename and endpoint to all Services
- added some more detailed action description - Browse, AddURI ...
- remove the info that 1 stands for true (is now in general section)
- info that some actions needs additional xml parsing
- corrected md error

2021-08-19 17:17 UTC, svrooij requested changes
I've checked all the changes and see some really good parts and some parts that don't work out very good.

This repository has several thinks

1. A manual created [documentation.json](https://github.com/svrooij/sonos-api-docs/blob/main/docs/documentation.json) file
2. Generator (which downloads service description and is able to generate files with templates), as described [here](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs)
3. (Mostly generated) [documentation files](https://github.com/svrooij/sonos-api-docs/tree/main/docs) that describe the how the sonos works.

On the [main page](https://svrooij.io/sonos-api-docs/#update-documentation) I've described how you should go about to update the documentation files. Since you manually updated the documentation files the next time I would generate them they would get lost. That is not what we want. 

You can then see the resulting documentation website by going to the [docs](https://github.com/svrooij/sonos-api-docs/tree/main/docs) folder and running `docker-compose up` (which obviously needs docker installed).

The markdown files are mostly generated by the generator running against [this template](https://github.com/svrooij/sonos-api-docs/tree/main/generator/sonos-docs/templates/docs). 

| Template | Resulting file(s) |
|-----------|------------------|
|[services-index.hbs](https://github.com/svrooij/sonos-api-docs/blob/main/generator/sonos-docs/templates/docs/services-index.hbs)|[services/index.md](https://github.com/svrooij/sonos-api-docs/blob/main/docs/services/index.md)
|[service.hbs](https://github.com/svrooij/sonos-api-docs/blob/main/generator/sonos-docs/templates/docs/service.hbs)| [services/*.md](https://github.com/svrooij/sonos-api-docs/tree/main/docs/services)|

2021-08-19 18:54 UTC, hklages commented on docs/documentation.json
> +      "description": "Control the sonos alarms. Service name:'AlarmClock', Endpoint: '/AlarmClock/Control' ",
Currently not the service name is the key but instead it is the service name + string "Service". My intention was to make clear, what the service name really is. 
What about: Remove the string "Service" from the "key".  Then the key is equal to the service name and the above is obsolete?

2021-08-19 18:59 UTC, hklages commented on docs/documentation.json
> +            "Unit": "What to seek. ",
Yes, but you automatically add the allowed values and without dot it looks like: 
`What to seek Allowed values: TRACK_NR / REL_TIME / TIME_DELTA`

2021-08-19 19:19 UTC, hklages commented on docs/documentation.json
> -            "DesiredValue": "DialogLevel and NightMode: 0 for off, 1 for on. SubGain between -10 and 10"
You are right. It is declared as integer and so it makes sense to leave this information.

2021-08-19 19:20 UTC, hklages commented on docs/documentation.json
> -            "DesiredLoudness": "true for on"
see comment to get crossfade mode

2021-08-19 19:27 UTC, hklages commented on docs/documentation.json
> +          "remarks":"Send to non-coordinator returns invalid value."
OK. What I mean with "invalid" is that the currently playing stream in that group may also allow next, previous, skip, ...
So only the coordinator provides the right information.

Maybe: Send to non-coordinator always returns Stop, Play but that may not be the transport actions of the stream currently being played in this group.

2021-08-19 19:28 UTC, hklages commented on docs/documentation.json
> -          "description": "Get crossfade mode, 1 for on, 0 for off",
In my opinion it is confusing that the type is declared as boolean and then we mention 1, 0 for SOME but not all parameter or properties. Either we should mention it everywhere (what is a lot of work) or nowhere. 

Its about "Consistency" - but feel free to reject. 

I added the general statement (boolean means 0 or 1) in the md-file (unfortunately it was the wrong place - sorry for that. I should have read the first page more carefully)  and removed everywhere the 0,1. 

I hope that it is obvious that GetCrossfadeMode, "Loudness", "Mute" and all other "Sonos boolean" get requests will return 1 for on and 0 for off.

2021-08-19 19:41 UTC, hklages commented
Sorry for changing the wrong file "index.md". I should have read the documentation in more detail. 
How shall we proceed?  We cancel the pull request and I send a new one only for the documention.json file?
What is your opinion about the content of the changes in index.md?

2021-08-19 20:10 UTC, svrooij commented
Please don't close this PR. Your input looks good, I'm currently trying to improve it for more consistency.

Did you give me write access in the branch? Then I'll update it and your hard work will still be present in the git history

2021-08-19 20:59 UTC, hklages commented
Thanks :-) 
Write access - have never done that. I send you an invitation for collaboration. Hope that works.

2021-08-19 21:20 UTC, svrooij commented on docs/documentation.json
> +      "description": "Control the sonos alarms. Service name:'AlarmClock', Endpoint: '/AlarmClock/Control' ",
According to the discovery file it's a collection of services. So every item in the collection is a **Service**. 😉 I must admit that this is legacy of the sonos libraries in node, and I would just like to keep it. In the templates there is also `{{name}}` instead of `{{serviceName}}` that has the name without `Service` after it. So if you just want the name changed in the docs, you could change that in the [template](generator/sonos-docs/templates/docs/service.hbs) and regenerate the docs.

2021-08-19 21:21 UTC, svrooij commented on docs/documentation.json
> -          "description": "Get crossfade mode, 1 for on, 0 for off",
I changed the templates to put the correct boolean values everywhere for consistency.

2021-08-19 21:22 UTC, svrooij commented on docs/documentation.json
> +          "remarks":"Send to non-coordinator returns invalid value."
It are the correct TransportActions for that speaker. That speaker is able to Play and Stop.

2021-08-19 21:24 UTC, svrooij commented on docs/documentation.json
> +            "Unit": "What to seek. ",
Hadn't seen your command before changing is back. maybe the template should include a comma before allowed values?

2021-08-19 21:28 UTC, svrooij commented
@hklages what do you think about the current state of the pr?

I've done the edit in Codespaces, which works awesome. I could even run the live preview docker container in it and see the page on my local machine while it was building (slowly at first start) in the cloud.

2021-08-20 05:54 UTC, hklages commented on docs/documentation.json
> +      "description": "Control the sonos alarms. Service name:'AlarmClock', Endpoint: '/AlarmClock/Control' ",
understand.

2021-08-20 05:55 UTC, hklages commented on docs/documentation.json
> +            "Unit": "What to seek. ",
As you like it. It just looked strange without anything.

2021-08-20 05:59 UTC, hklages commented
PR is fine for me. Do I have to do anything? 

Regarding Codespaces: I will have a look at this later. First I have to improve my PR management knowledge and reading documentations :-)

2021-08-20 06:15 UTC, merged